-- =============================================================================
-- Phase 2: task-attachments → private bucket with path-scoped access
-- =============================================================================
-- Layout: task-attachments/<project_id>/<task_id>/<filename>
-- (General/non-task uploads may use <project_id>/general/<filename>.)
--
-- Access rule: a user's own uploads plus any file under a project they
-- created or are a member of (or admins). Served via short-lived signed
-- URLs (15 min) generated by src/lib/attachments.ts — never raw public URLs.
--
-- WHY: the bucket was public=true, so any URL holder anywhere could fetch
-- hardware specs/CAD exports. The patch made it private but scoped reads to
-- "any approved user" only and uploads to "own UUID folder" — which broke
-- team sharing. Path-prefix scoping restores collaboration while enforcing
-- per-project confidentiality.
-- =============================================================================

-- Ensure bucket exists and is private
INSERT INTO storage.buckets (id, name, public)
VALUES ('task-attachments', 'task-attachments', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- ─── Helper: can user access files under this project folder? ────────────────
CREATE OR REPLACE FUNCTION public.can_access_project_files(
  bucket TEXT,
  object_name TEXT
)
RETURNS BOOLEAN AS $$
DECLARE
  proj_folder TEXT;
BEGIN
  IF bucket <> 'task-attachments' THEN
    RETURN false;
  END IF;

  -- First path segment is the folder (project id, or legacy user id)
  proj_folder := (storage.foldername(object_name))[1];

  -- Legacy layout: files under the uploader's own UUID folder remain readable
  -- by owner + admins.
  IF proj_folder = auth.uid()::text OR public.is_admin(auth.uid()) THEN
    RETURN true;
  END IF;

  -- Project layout: creator or member of that project.
  RETURN proj_folder IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.projects p
    WHERE p.id::text = proj_folder
      AND (
        p.created_by = auth.uid() OR
        EXISTS (
          SELECT 1 FROM public.project_members pm
          WHERE pm.project_id = p.id AND pm.user_id = auth.uid()
        )
      )
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp, storage STABLE;

-- ─── Storage policies ────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Users upload to own folder"              ON storage.objects;
DROP POLICY IF EXISTS "Approved users can read attachments"     ON storage.objects;
DROP POLICY IF EXISTS "Project-scoped attachment read"          ON storage.objects;
DROP POLICY IF EXISTS "Project-scoped attachment upload"        ON storage.objects;

CREATE POLICY "Project-scoped attachment upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (public.can_access_project_files(bucket_id, name));

CREATE POLICY "Project-scoped attachment read"
  ON storage.objects FOR SELECT TO authenticated
  USING (public.can_access_project_files(bucket_id, name));
